const menu = [
  {
    id: 1,
    title: 'Garlic Bread',
    category: 'Appetizers',
    price: 5.99,
    img: './images/item-1.jpeg',
    desc: `Homemade bread with garlic & herb spread. `,
  },
  {
    id: 2,
    title: 'Cheese bread',
    category: 'Appetizers',
    price: 7.99,
    img: './images/item-2.jpeg',
    desc: `Homemade bread with garlic, herb and cheese blend. `,
  },
  {
    id: 3,
    title: 'Roasted Butternut Squash',
    category: 'Appetizers',
    price: 10.99,
    img: './images/item-3.jpeg',
    desc: `with caramelized onion, gorgonzola, and walnuts. `,
  },
  {
    id: 4,
    title: 'Margherita Zucchini Boat',
    category: 'Appetizers',
    price: 10.95,
    img: './images/item-4.jpeg',
    desc: `Zucchini with mozzarella, fresh tomato, garlic, parmesan, and fresh basil. `,
  },
  {
    id: 5,
    title: 'Wings',
    category: 'Appetizers',
    price: 10.99,
    img: './images/item-5.jpeg',
    desc: `No breading, no frying. Baked and charred. Tossed in mild buffalo wing sauce (8 pieces). Served with ranch dressing.`,
  },
  {
    id: 6,
    title: 'Mozzarella Sticks',
    category: 'Appetizers',
    price: 10.99,
    img: './images/item-6.jpeg',
    desc: `Served with homemade marinara sauce.`,
  },
  {
    id: 7,
    title: 'Pepperoni Chips',
    category: 'Appetizers',
    price: 7.99,
    img: './images/item-7.jpeg',
    desc: `Crispy, crunchy pepperoni. Served with ranch dressing.`,
  },
  {
    id: 8,
    title: 'Pepperoni',
    category: 'Pizzas',
    price: 11.99,
    img: './images/item-8.jpeg',
    desc: `Tomato sauce, mozzarella, and pepperoni. `,
  },
  {
    id: 9,
    title: 'Hawaiin',
    category: 'Pizzas',
    price: 13.25,
    img: './images/item-9.jpeg',
    desc: `Tomato sauce, Mozzarella, Canadian bacon, onion, fresh pineapple.`,
  },
  {
    id: 10,
    title: 'Chicken Sausage',
    category: 'Pizzas',
    price: 13.50,
    img: './images/item-10.jpeg',
    desc: `Tomato sauce, mozzarella, CasCioppo Bros chicken sausage, olives, garlic, and fresh basil.`,
  },
  {
    id: 11,
    title: 'Italian Sausage',
    category: 'Pizzas',
    price: 13.50,
    img: './images/item-11.jpeg',
    desc: `Tomato sauce, mozzarella, Cascioppo Bros sausage, fresh mushroom, and onion.`,
  },
  {
    id: 12,
    title: 'BBQ Chicken',
    category: 'Pizzas',
    price: 13.25,
    img: './images/item-12.jpeg',
    desc: `BBQ sauce, mozzarella, chicken, onion, topped with fresh cilantro.`,
  },
  {
    id: 13,
    title: 'Truffle Bianco',
    category: 'Pizzas',
    price: 13.25,
    img: './images/item-13.jpeg',
    desc: `Mozzarella, pecorino Romano, truffle oil, garlic, fresh basil, kosher salt (on the side).`,
  },
  {
    id: 14,
    title: 'Chicken Pesto',
    category: 'Pizzas',
    price: 13.25,
    img: './images/item-14.jpeg',
    desc: `Pesto sauce, mozzarella, chicken breast, artichoke hearts, and sun-dried tomato.`,
  },
  {
    id: 15,
    title: 'Waikiki',
    category: 'Pizzas',
    price: 13.50,
    img: './images/item-15.jpeg',
    desc: `Buffalo wing sauce, mozzarella, chicken breast, onion, olives, and blue cheese. `,
  },
  {
    id: 16,
    title: 'Cape "D" Delight',
    category: 'Pizzas',
    price: 13.50,
    img: './images/item-16.jpeg',
    desc: `Garlic parmesan oil, chicken, mozzarella, sun-dried tomato, onion, cashew, gorgonzola, and fresh basil.`,
  },
  {
    id: 17,
    title: 'Mediterranean',
    category: 'Pizzas',
    price: 13.25,
    img: './images/item-17.jpeg',
    desc: `Garlic parmesan oil, mozzarella, chicken, olives, onion, sun-dried tomato, and feta.`,
  },
  {
    id: 18,
    title: 'Chicken Alfredo',
    category: 'Pizzas',
    price: 13.50,
    img: './images/item-18.jpeg',
    desc: `Alfredo sauce, mozzarella, chicken, onion, mushroom, and bell pepper.`,
  },
  {
    id: 19,
    title: 'The Boreas',
    category: 'Pizzas',
    price: 13.50,
    img: './images/item-19.jpeg',
    desc: `Garlic parmesan oil, mozzarella, pepperoni, olives, artichoke hearts, sun-dried tomato, and feta..`,
  },
  {
    id: 20,
    title: 'Meat Lover',
    category: 'Pizzas',
    price: 13.50,
    img: './images/item-20.jpeg',
    desc: `Tomato sauce, mozzarella, Canadian bacon, sausage, pepperoni, olives, onion, and fresh mushroom.`,
  },
  {
    id: 21,
    title: 'Skookum',
    category: 'Pizzas',
    price: 13.50,
    img: './images/item-21.jpeg',
    desc: `Tomato sauce, mozzarella, chicken & pork sausage, onion, olives, garlic, pepper flakes, and fresh basil.`,
  },
  {
    id: 22,
    title: 'Mixed Green',
    category: 'Salads',
    price: 7.50,
    img: './images/item-23.jpeg',
    desc: `Organic mixed green topped with red onion and croutons. Your choice of ranch or balsamic vinaigrette. `,
  },
  {
    id: 23,
    title: 'Caesar',
    category: 'Salads',
    price: 8.50,
    img: './images/item-24.jpeg',
    desc: `Romain hearts tossed in housemate caesar dressing, croutons & parmesan.`,
  },
  {
    id: 24,
    title: 'Arugula',
    category: 'Salads',
    price: 8.50,
    img: './images/item-25.jpeg',
    desc: `Arugula, fresh tomato, onion, candied walnuts, parmesan, balsamic vinaigrette.`,
  },
  {
    id: 25,
    title: 'Pear & Gorgonzola',
    category: 'Salads',
    price: 8.50,
    img: './images/item-22.jpeg',
    desc: `Organic mixed green, pear, gorgonzola, candied walnuts, balsamic vinaigrette.`,
  },
  {
    id: 26,
    title: 'Caprese',
    category: 'Salads',
    price: 8.99,
    img: './images/item-26.jpeg',
    desc: `Mixed green, fresh mozzarella, fresh tomato, fresh basil, balsamic vinaigrette.`,
  },
  {
    id: 27,
    title: 'CANNOLI',
    category: 'Desserts',
    price: 3.99,
    img: './images/item-27.jpeg',
    desc: `With sweet Vanilla cream `,
  },
  {
    id: 28,
    title: 'Roasted Veggies',
    category: 'Sandwiches',
    price: 13.25,
    img: './images/item-28.jpeg',
    desc: `Bell pepper, fresh tomato, mushroom, artichoke hearts, onion, pesto, topped with melted provolone.`,
  },
  {
    id: 29,
    title: 'BBQ Chicken',
    category: 'Sandwiches',
    price: 13.50,
    img: './images/item-29.jpeg',
    desc: `BBQ sauce, chicken, melted mozzarella, and caramelized onion.`,
  },
  {
    id: 30,
    title: 'Buffalo Chicken',
    category: 'Sandwiches',
    price: 13.95,
    img: './images/item-30.jpeg',
    desc: `Homemade buffalo wing sauce, chicken, onion, bell pepper, provolone, and gorgonzola. Ranch on the side.`,
  },
  
];
export default menu;
